- hosts: tempest
  vars:
    tox_envlist: functional
  roles:
    - fetch-subunit-output
    - fetch-devstack-log-dir
    - fetch-output
    - role: "src/opendev.org/openstack/validations-common/roles/fetch_validations"
    - fetch-python-sdist-output
